# Generated by Django 2.0.3 on 2020-02-12 15:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ApiManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SDKTestInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('sdk_name', models.CharField(max_length=50, verbose_name='SDK文件名称')),
                ('test_name', models.CharField(max_length=50, verbose_name='测试文件名称')),
                ('others', models.CharField(max_length=200, null=True, verbose_name='其它文件')),
                ('author', models.CharField(max_length=20, verbose_name='上传人员')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间')),
                ('belong_module', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ApiManager.ModuleInfo')),
                ('belong_project', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ApiManager.ProjectInfo')),
            ],
            options={
                'verbose_name': 'SDK测试信息管理',
                'db_table': 'SDKTestInfo',
            },
        ),
        migrations.AddField(
            model_name='testreports',
            name='author',
            field=models.CharField(default='', max_length=100),
        ),
    ]
