# Generated by Django 2.0.2 on 2019-08-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testreports',
            name='report_name',
            field=models.CharField(max_length=100),
        ),
    ]
