# Generated by Django 2.0.3 on 2020-04-07 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiManager', '0003_auto_20200224_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaCFG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('ca_url', models.CharField(max_length=500, verbose_name='CA请求地址')),
                ('ca_loginurl', models.CharField(max_length=500, verbose_name='CA登录地址')),
            ],
            options={
                'verbose_name': 'CA基础配置',
                'db_table': 'CaCfg',
            },
        ),
        migrations.CreateModel(
            name='CaInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user_name', models.CharField(max_length=50, verbose_name='用户名称')),
                ('author', models.CharField(max_length=50, null=True, verbose_name='添加人员')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('value', models.TextField(null=True, verbose_name='ca值')),
                ('redirect_url', models.URLField(max_length=100, verbose_name='redirect_url')),
                ('client_id', models.CharField(max_length=50, verbose_name='客户端名称')),
                ('password', models.CharField(default='', max_length=50, verbose_name='密码')),
                ('expire_time', models.DateTimeField(verbose_name='到期时间')),
                ('belong_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiManager.ProjectInfo')),
            ],
            options={
                'verbose_name': 'CA信息管理',
                'db_table': 'CaInfo',
            },
        ),
        migrations.AddField(
            model_name='testcaseinfo',
            name='ca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ApiManager.CaInfo'),
        ),
    ]
