# Generated by Django 2.0.3 on 2020-04-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiManager', '0004_auto_20200407_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cainfo',
            name='expire_time',
        ),
        migrations.RemoveField(
            model_name='cainfo',
            name='status',
        ),
        migrations.RemoveField(
            model_name='cainfo',
            name='value',
        ),
        migrations.AddField(
            model_name='cacfg',
            name='ca_type',
            field=models.CharField(default='dev', max_length=50, verbose_name='CA类型'),
        ),
        migrations.AlterField(
            model_name='cainfo',
            name='redirect_url',
            field=models.CharField(default='@@@redirect_url@@@', max_length=100, verbose_name='redirect_url'),
        ),
    ]
