# Generated by Django 2.0.3 on 2019-11-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiManager', '0004_auto_20190902_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envinfo',
            name='base_url',
            field=models.CharField(max_length=100),
        ),
    ]
