# Generated by Django 2.0.3 on 2020-06-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiManager', '0005_auto_20200420_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envinfo',
            name='base_url',
            field=models.CharField(max_length=200),
        ),
    ]
