# Generated by Django 2.0.3 on 2020-07-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiManager', '0006_auto_20200609_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdktestinfo',
            name='sdk_name',
            field=models.CharField(max_length=500, verbose_name='SDK文件名称'),
        ),
    ]
