# Generated by Django 2.0.3 on 2020-07-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiManager', '0007_auto_20200703_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcaseinfo',
            name='name',
            field=models.CharField(max_length=100, verbose_name='用例/配置名称'),
        ),
    ]
