# Generated by Django 2.0.3 on 2019-10-16 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiManager', '0004_auto_20190902_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileinfo',
            name='file_path',
            field=models.CharField(default='', max_length=100, verbose_name='文件路径'),
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ApiManager.ModuleInfo'),
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ApiManager.ProjectInfo'),
        ),
    ]
